version: '3.1'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: kaikeba666
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
  